### ISSUE TITLE
Test failures on master branch

### ISSUE THREAD

**Issue by lahirus** [wso2/carbon-health-check#30]
**Description:**

Referred at doc https://apim.docs.wso2.com/en/latest/administer/logging-and-monitoring/monitoring/monitoring-server-health/#monitoring-server-health

Error:

mvn clean install
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] org.wso2.carbon.healthcheck.parent
[INFO] org.wso2.carbon.healthcheck.api.core
[INFO] org.wso2.carbon.healthcheck.api.endpoint
[INFO] WSO2 Carbon - Health Check API feature
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building org.wso2.carbon.healthcheck.parent 1.2.15-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ org.wso2.carbon.healthcheck.parent ---
[INFO] Deleting /Users/lahirugmg/work/wso2/support/sep-2021/400/carbon-health-check/target
[INFO]
[INFO] --- maven-remote-resources-plugin:1.6.0:process (default) @ org.wso2.carbon.healthcheck.parent ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Preparing remote bundle org.apache:apache-jar-resource-bundle:1.4
[INFO] Copying 3 resources from 1 bundle.
[INFO]
[INFO] --- maven-javadoc-plugin:3.1.1:jar (attach-javadocs) @ org.wso2.carbon.healthcheck.parent ---
[INFO] Not executing Javadoc as the project is not a Java classpath-capable package
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ org.wso2.carbon.healthcheck.parent ---
[INFO] Installing /Users/lahirugmg/work/wso2/support/sep-2021/400/carbon-health-check/pom.xml to /Users/lahirugmg/.m2/repository/org/wso2/carbon/healthcheck/org.wso2.carbon.healthcheck.parent/1.2.15-SNAPSHOT/org.wso2.carbon.healthcheck.parent-1.2.15-SNAPSHOT.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building org.wso2.carbon.healthcheck.api.core 1.2.15-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ org.wso2.carbon.healthcheck.api.core ---
[INFO] Deleting /Users/lahirugmg/work/wso2/support/sep-2021/400/carbon-health-check/components/org.wso2.carbon.healthcheck.api.core/target
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.9:prepare-agent (default-prepare-agent) @ org.wso2.carbon.healthcheck.api.core ---
[INFO] argLine set to -javaagent:/Users/lahirugmg/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/Users/lahirugmg/work/wso2/support/sep-2021/400/carbon-health-check/components/org.wso2.carbon.healthcheck.api.core/target/jacoco.exec
[INFO]
[INFO] --- build-helper-maven-plugin:3.0.0:add-source (add-source) @ org.wso2.carbon.healthcheck.api.core ---
[INFO] Source directory: /Users/lahirugmg/work/wso2/support/sep-2021/400/carbon-health-check/components/org.wso2.carbon.healthcheck.api.core/src/gen/java added.
[INFO]
[INFO] --- maven-remote-resources-plugin:1.6.0:process (default) @ org.wso2.carbon.healthcheck.api.core ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Preparing remote bundle org.apache:apache-jar-resource-bundle:1.4
[INFO] Copying 3 resources from 1 bundle.
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ org.wso2.carbon.healthcheck.api.core ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/lahirugmg/work/wso2/support/sep-2021/400/carbon-health-check/components/org.wso2.carbon.healthcheck.api.core/src/main/resources
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ org.wso2.carbon.healthcheck.api.core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 20 source files to /Users/lahirugmg/work/wso2/support/sep-2021/400/carbon-health-check/components/org.wso2.carbon.healthcheck.api.core/target/classes
[INFO] /Users/lahirugmg/work/wso2/support/sep-2021/400/carbon-health-check/components/org.wso2.carbon.healthcheck.api.core/src/main/java/org/wso2/carbon/healthcheck/api/core/JavaMemoryUsageLogger.java: Some input files use unchecked or unsafe operations.
[INFO] /Users/lahirugmg/work/wso2/support/sep-2021/400/carbon-health-check/components/org.wso2.carbon.healthcheck.api.core/src/main/java/org/wso2/carbon/healthcheck/api/core/JavaMemoryUsageLogger.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ org.wso2.carbon.healthcheck.api.core ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 2 resources
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ org.wso2.carbon.healthcheck.api.core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Users/lahirugmg/work/wso2/support/sep-2021/400/carbon-health-check/components/org.wso2.carbon.healthcheck.api.core/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ org.wso2.carbon.healthcheck.api.core ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[WARNING] Corrupted stdin stream in forked JVM 1. See the dump file /Users/lahirugmg/work/wso2/support/sep-2021/400/carbon-health-check/components/org.wso2.carbon.healthcheck.api.core/target/surefire-reports/2021-09-01T16-08-23_119-jvmRun1.dumpstream
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] org.wso2.carbon.healthcheck.parent ................. SUCCESS [  1.475 s]
[INFO] org.wso2.carbon.healthcheck.api.core ............... FAILURE [  8.303 s]
[INFO] org.wso2.carbon.healthcheck.api.endpoint ........... SKIPPED
[INFO] WSO2 Carbon - Health Check API feature ............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.729 s
[INFO] Finished at: 2021-09-01T16:08:24-05:00
[INFO] Final Memory: 33M/512M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20:test (default-test) on project org.wso2.carbon.healthcheck.api.core: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/lahirugmg/work/wso2/support/sep-2021/400/carbon-health-check/components/org.wso2.carbon.healthcheck.api.core/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/lahirugmg/work/wso2/support/sep-2021/400/carbon-health-check/components/org.wso2.carbon.healthcheck.api.core && /Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home/bin/java -javaagent:/Users/lahirugmg/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/Users/lahirugmg/work/wso2/support/sep-2021/400/carbon-health-check/components/org.wso2.carbon.healthcheck.api.core/target/jacoco.exec -jar /Users/lahirugmg/work/wso2/support/sep-2021/400/carbon-health-check/components/org.wso2.carbon.healthcheck.api.core/target/surefire/surefirebooter12699067814028732533.jar /Users/lahirugmg/work/wso2/support/sep-2021/400/carbon-health-check/components/org.wso2.carbon.healthcheck.api.core/target/surefire 2021-09-01T16-08-23_119-jvmRun1 surefire18336787049027549615tmp surefire_085311412947079516tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 134
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/lahirugmg/work/wso2/support/sep-2021/400/carbon-health-check/components/org.wso2.carbon.healthcheck.api.core && /Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home/bin/java -javaagent:/Users/lahirugmg/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/Users/lahirugmg/work/wso2/support/sep-2021/400/carbon-health-check/components/org.wso2.carbon.healthcheck.api.core/target/jacoco.exec -jar /Users/lahirugmg/work/wso2/support/sep-2021/400/carbon-health-check/components/org.wso2.carbon.healthcheck.api.core/target/surefire/surefirebooter12699067814028732533.jar /Users/lahirugmg/work/wso2/support/sep-2021/400/carbon-health-check/components/org.wso2.carbon.healthcheck.api.core/target/surefire 2021-09-01T16-08-23_119-jvmRun1 surefire18336787049027549615tmp surefire_085311412947079516tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 134
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:679)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:279)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:243)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1077)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:907)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:785)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[ERROR] at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
[ERROR] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.wso2.carbon.healthcheck.api.core

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Run `mvn clean install` after checkout

**Related Issues:**

**Comment by cmullins08008** [comment]
I ran into the same issue when compiling with openJDK 11.

I was successful when compiling with openJDK 8.
